In [283]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5
print(arr)

[[48 13 92 21 26]
 [32 56 57 97 76]
 [17 58 22 18 69]
 [39 40 93 42 53]
 [73 55 91 46 64]
 [37 68 96 48  7]
 [89 63 11 85 65]
 [70 62 46 34 83]
 [65 55 63 13  9]
 [69 25 26 71 57]]


In [284]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[48, 13, 92, 21, 26, 32, 56, 57, 97, 76],
       [17, 58, 22, 18, 69, 39, 40, 93, 42, 53],
       [73, 55, 91, 46, 64, 37, 68, 96, 48,  7],
       [89, 63, 11, 85, 65, 70, 62, 46, 34, 83],
       [65, 55, 63, 13,  9, 69, 25, 26, 71, 57]], dtype=int32)

In [285]:
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'C')

print(column_wise_flattening)

1
[48 13 92 21 26 32 56 57 97 76 17 58 22 18 69 39 40 93 42 53 73 55 91 46
 64 37 68 96 48  7 89 63 11 85 65 70 62 46 34 83 65 55 63 13  9 69 25 26
 71 57]


In [286]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
c = a + b
print(a)
print(b)
print(c)

[[5 3 4]
 [8 9 1]]
[[29 23 24]
 [26 26 20]]
[[34 26 28]
 [34 35 21]]


In [287]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 5  3  4]
 [ 8  9  1]
 [29 23 24]
 [26 26 20]]
[[ 5  3  4 29 23 24]
 [ 8  9  1 26 26 20]]


In [288]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
# r = np.concatenate((x,y),axis =1 )
print(r)

[[5 4 5]
 [6 3 7]
 [9 2 5]]


In [289]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [290]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
# splitted_array = np.split(a,3)

[6 9 3 2 8 6 3 3 4 4]
[array([6, 9, 3, 2], dtype=int32), array([8, 6, 3], dtype=int32), array([3, 4, 4], dtype=int32)]


In [291]:
# arithmetic operator and mathematical functions

# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [292]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [293]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [294]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [295]:
# Logical Function
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


In [296]:
# Sorting:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()
print(z)
z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [297]:
# copy sorting
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [298]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [299]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [300]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [301]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


In [302]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[24 17 26 45  3 25 80 86 94 61 14 94 91  6 15 77 49 20  2 22 18 50 65 93
 64 98 15 82 19 55 29 64  6  7 10 72 19  5  9 11 94 54 32 18 53 15 85 57
 89  8 47 53 88 14 12 49 96 25 81 14 15 87 81 75 61 38 14 48 53 57 85 82
 80 58 36 17 52 29  2 30 84 77  4 14 22 89 71 40 47 50 78 19 85 87 90 47
 52 88 22  7]


In [303]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

0


In [304]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 2  3  4  5  6  7  8  9 10 11 12 14 15 17 18 19 20 22 24 25 26 29 30 32
 36 38 40 45 47 48 49 50 52 53 54 55 57 58 61 64 65 71 72 75 77 78 80 81
 82 84 85 86 87 88 89 90 91 93 94 96 98]
[2 1 1 1 2 2 1 1 1 1 1 5 4 2 2 3 1 3 1 2 1 2 1 1 1 1 1 1 3 1 2 2 2 3 1 1 2
 1 2 2 1 1 1 1 2 1 2 2 2 1 3 1 2 2 2 1 1 1 3 1 1]


In [305]:
# statistical function
#data load

# data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

# print(data)

In [306]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

In [ ]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

In [ ]:
# linear algebra
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)

# trace
print(np.trace(B))

In [ ]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))